agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/core-ubuntu-2204

steps:
  - label: "DLQ rspec integration test"
    command: ./.buildkite/scripts/setup_java.sh && ./ci/serverless/dlq_rspec_tests.sh
  - label: "es-output test"
    command: ./.buildkite/scripts/setup_java.sh && ./ci/serverless/es_output_tests.sh
  - label: "es-input test"
    command: ./.buildkite/scripts/setup_java.sh && ./ci/serverless/es_input_tests.sh
  - label: "es-filter test"
    command: ./.buildkite/scripts/setup_java.sh && ./ci/serverless/es_filter_tests.sh
  - label: "elastic_integration filter test"
    command: ./.buildkite/scripts/setup_java.sh && ./ci/serverless/elastic_integration_filter_tests.sh
  - label: "central pipeline management test"
    command: ./.buildkite/scripts/setup_java.sh && ./ci/serverless/cpm_tests.sh
# Legacy monitoring is disabled. Serverless does not support /_monitoring/bulk, hence the test always fails to ingest metrics.
- label: "Logstash legacy monitoring test"
  command: ./.buildkite/scripts/setup_java.sh && ./ci/serverless/monitoring_tests.sh
  skip: true
  - label: "Kibana API test"
    command: ./.buildkite/scripts/setup_java.sh && ./ci/serverless/kibana_api_tests.sh
  - label: "metricbeat stack monitoring test"
    command: ./.buildkite/scripts/setup_java.sh && ./ci/serverless/metricbeat_monitoring_tests.sh