metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

output.elasticsearch:
  hosts: ["${ES_ENDPOINT}"]
  protocol: "https"
  api_key: "${MB_API_KEY}"

metricbeat.modules:
  - module: logstash
    metricsets:
      - node
      - node_stats
    period: 10s
    hosts:
        - localhost:9600
    xpack.enabled: true